stages:
  - deploy

deploy:
  # only:
  #   - tags
  stage: deploy
  image: alpine:latest
  tags:
    - docker
  script:
    - apk add curl ca-certificates
    - cp /tls/epgi-prod-ca.crt /usr/local/share/ca-certificates/
    - update-ca-certificates
    - 'curl --fail-with-body --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'